const $=id=>document.getElementById(id)||{},e=s=>String(s??'').replace(/[&<>"]/g,c=>'&#'+c.charCodeAt(0)+';');
const L=a=>a.map(x=>`<li>${e(x)}</li>`).join('');
const asset=x=>{x=String(x);const m=x.match(/^(.*?)\s*\((.+)\)$/);const c=/\$\s?\d+\s*FAAB/i.test(x)?'faab':/\b(1st|2nd|3rd|4th)\b|round|\bpick\b/i.test(x)?'pick':'pl';return `<li class="bd ${c}">${c==='pl'&&m?`<b>${e(m[1])}</b> <small>${e(m[2])}</small>`:e(x)}</li>`};
const AL=a=>`<ul class="assets">${a.map(asset).join('')}</ul>`;
const money=n=>n?'$'+n:'$0';
const pre=(m,cls='')=>`<details class="pg acc ${cls}" ${cls?'open':''}><summary><div class="vs"><div><small>${e(m.ar)}</small>${e(m.a)}<b>${m.pa}</b><i>${m.wa}%</i></div><span>VS</span><div class="r"><small>${e(m.br)}</small>${e(m.b)}<b>${m.pb}</b><i>${m.wb}%</i></div></div><div class="bar"><u style="width:${m.wa}%"></u></div></summary><div class="cols"><div><h5>Must get right: ${e(m.a)}</h5><p>${e(m.ma)}</p><h5>Landmines</h5><p>${e(m.la)}</p></div><div><h5>Must get right: ${e(m.b)}</h5><p>${e(m.mb)}</p><h5>Landmines</h5><p>${e(m.lb)}</p></div></div><p class="edge"><b>Edge</b> ${e(m.edge)}</p><p class="desk">${e(m.desk)}</p></details>`;
const post=m=>{const aw=m.sa>m.sb;return `<details class="pg acc"><summary><div class="vs"><div class="${aw?'w':'l'}"><small>${e(m.ar)}</small>${e(m.a)}<b>${m.sa}</b></div><span>VS</span><div class="r ${aw?'l':'w'}"><small>${e(m.br)}</small>${e(m.b)}<b>${m.sb}</b></div></div></summary><p class="tag">${e(m.tag)}</p><div class="cols"><div><h5>How the projection aged</h5><ul>${L(m.aged)}</ul></div><div><h5>What it means</h5><ul>${L(m.means)}</ul></div><div><h5>Key decision</h5><ul>${L(m.key)}</ul></div><div class="stat"><table><tr><th></th><th class="n">${e(m.a)}</th><th class="n">${e(m.b)}</th></tr><tr><td>Bench</td><td class="n">${e(m.ba)}</td><td class="n">${e(m.bb)}</td></tr><tr><td>MVP</td><td class="n">${e(m.ma)}</td><td class="n">${e(m.mb)}</td></tr><tr><td>Grade</td><td class="n g">${e(m.ga)}</td><td class="n g">${e(m.gb)}</td></tr></table></div></div><p class="desk">${e(m.desk)}</p></details>`};
const side=(n,r,i,h)=>`<div><small>${e(n)} receives</small>${AL(r)}<h5>Immediate impact</h5><p>${e(i)}</p><h5>Dynasty horizon</h5><p>${e(h)}</p></div>`;
const inline=document.getElementById('issue-data');
const load=inline?Promise.resolve(JSON.parse(inline.textContent)):fetch('../../../data/issues/'+location.pathname.split('/').filter(p=>/^issue-\d+$/.test(p)).pop()+'.json').then(r=>{if(!r.ok)throw new Error(r.status);return r.json()});
load.then(d=>{
const s=d.standings;
$('stand').innerHTML=`<div class="sc"><table><thead><tr><th class="n">#</th><th>Team</th><th class="n">W-L</th><th class="n">MOV</th><th class="n">PF</th><th class="n">PA</th><th class="n">FAAB</th><th class="n">PRI</th><th class="n">MAXPF</th><th class="n">DRFT</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td class="n">${r[0]}<td><b>${e(r[1])}</b><td class="n">${r[2]}<td class="n ${r[3]=='▲'?'up':r[3]=='▼'?'dn':''}">${r[3]}<td class="n">${r[4].toFixed(2)}<td class="n">${r[5].toFixed(2)}<td class="n">${money(r[6])}<td class="n">${r[7]}<td class="n">${r[8].toFixed(2)}<td class="n">${r[9]}`).join('')}</tbody></table></div><p class="key">${e(s.key)}</p>`;
$('bank').innerHTML=`<div class="bank">${s.bank.map(b=>`<div><small>${e(b[0])}</small><b>${e(b[1])}</b><i class="${b[2].startsWith('-')?'dn':b[2].startsWith('+')?'up':''}">${e(b[2])}</i><p>${e(b[3])}</p></div>`).join('')}</div>`;
const w=d.wire;
$('wire-box').innerHTML=`<div class="star red">Breaking: trades cleared</div><div class="tm">${w.trades.map(t=>`<article class="tc"><h3>${e(t.a)} &harr; ${e(t.b)}</h3><div class="sides">${side(t.a,t.ar,t.ai,t.ah)}${side(t.b,t.br,t.bi,t.bh)}</div><p class="grades"><b>${e(t.ga)}</b><b>${e(t.gb)}</b></p><p class="desk">${e(t.desk)}</p></article>`).join('')}</div><h3 class="sub">Waiver transactions</h3><div class="wire">${w.waivers.map(x=>`<div class="${x[4]||''}"><span><b>${e(x[0])}</b></span><span class="a">+ ${e(x[1])}${x[3]?` <span class="d">&minus; ${e(x[3])}</span>`:''}</span><small>${money(x[2])}${x[4]=='mvp'?' &middot; WAIVER WIRE MVP':x[4]?' &middot; DESK FAVORITE':''}</small>${x[4]?`<img class="bdg" src="../../../assets/badge-${x[4]=='mvp'?'mvp':'desk'}.png" alt="">`:''}${x[5]?`<p class="desk">${e(x[5])}</p>`:''}</div>`).join('')}</div>`;
$('postcards').innerHTML=d.post.map(post).join('');
$('quote').innerHTML=`<blockquote>&ldquo;${e(d.quote.text)}&rdquo;</blockquote><p class="by">${e(d.quote.by)}</p><p class="desk">${e(d.quote.desk)}</p>`;
$('drama-list').innerHTML=d.drama.map(x=>`<article class="dr"><span class="heat">${x.heat}&deg;</span><div><h3>${e(x.h)}</h3><p>${e(x.p)}</p><p class="desk">${e(x.desk)}</p></div></article>`).join('')+`<h3 class="sub">Chat greatest hits</h3><div class="hits">${d.hits.map(h=>`<figure><blockquote>&ldquo;${e(h[0])}&rdquo;</blockquote><figcaption>${e(h[1])}</figcaption></figure>`).join('')}</div>`;
$('trades-box').innerHTML=`<p class="art">${e(d.trades.note)}</p><div class="tm">${d.trades.items.map((t,i)=>`<article class="tc"><h3>${i+1}. ${e(t.t)}</h3><div class="sides"><div><small>${e(t.a)} sends</small>${AL(t.as)}<p>${e(t.ay)}</p></div><div class="r"><small>${e(t.b)} sends</small>${AL(t.bs)}<p>${e(t.by)}</p></div></div><p class="desk">${e(t.desk)}</p></article>`).join('')}</div>`;
$('pre').innerHTML=d.pre.map(m=>pre(m)).join('');
const m=d.motw;
$('motw').innerHTML=`<div class="star badge"><img class="bdg lg" src="../../../assets/badge-motw.png" alt="Match of the Week"></div>${pre(m,'big')}<div class="sg"><div class="sc"><table><thead><tr><th>Metric</th><th class="n">${e(m.a)}</th><th class="n">${e(m.b)}</th></tr></thead><tbody>${m.stats.map(r=>`<tr><td>${e(r[0])}<td class="n">${e(r[1])}<td class="n">${e(r[2])}`).join('')}</tbody></table></div><div><h4>The stakes</h4><p>${e(m.stakes)}</p></div></div><div class="sw">${m.sw.map(x=>`<div><h4>${e(x[0])}</h4><h5>Strengths</h5><ul>${L(x[1])}</ul><h5>Weak links</h5><ul>${L(x[2])}</ul></div>`).join('')}</div><div class="verdict"><h4>Final verdict</h4><p>${e(m.verdict)}</p><b>${e(m.a)} ${m.pa.toFixed(1)}</b><b class="r">${e(m.b)} ${m.pb.toFixed(1)}</b></div>`;
$('power-box').innerHTML=`<div class="sc"><table><thead><tr><th class="n">#</th><th>Team</th><th class="n">W-L</th><th class="n">MOV</th><th class="n">Avg age</th><th class="n">Fut cap</th><th class="n">Drft</th><th>The verdict</th></tr></thead><tbody>${d.power.rows.map(r=>`<tr><td class="n">${r[0]}<td><b>${e(r[1])}</b><td class="n">${r[2]}<td class="n ${r[3]=='▲'?'up':r[3]=='▼'?'dn':''}">${r[3]}<td class="n">${r[4]}<td class="n">${r[5]}<td class="n">${r[6]}<td>${e(r[7])}`).join('')}</tbody></table></div><p class="key">${e(d.power.key)}</p><h3 class="sub">Bold predictions</h3><div class="bold">${d.power.bold.map(b=>`<div><h4>${e(b[0])}</h4><p>${e(b[1])}</p></div>`).join('')}</div>`;
$('bottom').innerHTML=`<div class="art">${d.bottom.paras.map(t=>`<p>${e(t)}</p>`).join('')}<p class="desk"><b>How MAXPF works.</b> ${e(d.bottom.maxpf)}</p></div>`;
const p=d.poll,k='poll-'+p.id;let v=null;try{v=localStorage.getItem(k)}catch(_){}
const done=c=>$('poll').innerHTML=`<h3>${e(p.q)}</h3><p class="thanks">Vote logged: <b>${e(p.opts[c])}</b>.${p.endpoint?'':' (Saved on this device only. Add a poll endpoint to count league-wide votes.)'}</p>`;
if(v!==null)done(+v);else{$('poll').innerHTML=`<h3>${e(p.q)}</h3><div class="opts">${p.opts.map((o,i)=>`<label><input type="radio" name="pv" value="${i}"> <span>${'ABCD'[i]}</span> ${e(o)}</label>`).join('')}</div><button class="btn" id="vote" disabled>Cast vote</button><p class="desk">${e(p.desk)}</p>`;
document.querySelectorAll('[name=pv]').forEach(r=>r.onchange=()=>$('vote').disabled=false);
$('vote').onclick=()=>{const c=+document.querySelector('[name=pv]:checked').value;
if(p.endpoint)fetch(p.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({poll:p.id,choice:p.opts[c]})}).catch(()=>{});
try{localStorage.setItem(k,c)}catch(_){}done(c)}}
}).catch(err=>{console.error(err);const b=document.createElement('p');b.className='loaderr';b.textContent='Issue content failed to load. If you opened this file from your computer, view it on the live site, or run scripts/build_site.py to embed the data.';document.querySelector('main').prepend(b)});
